In [63]:
from qiskit.providers.fake_provider import FakeLima, FakeBelem

In [13]:
FakeLima().properties().to_dict()

{'backend_name': 'ibmq_lima',
 'backend_version': '1.0.5',
 'last_update_date': datetime.datetime(2021, 3, 15, 0, 36, 3, tzinfo=tzoffset(None, -14400)),
 'qubits': [[{'date': datetime.datetime(2021, 3, 15, 0, 9, 11, tzinfo=tzoffset(None, -14400)),
    'name': 'T1',
    'unit': 'us',
    'value': 59.69864328663569},
   {'date': datetime.datetime(2021, 3, 15, 0, 9, 44, tzinfo=tzoffset(None, -14400)),
    'name': 'T2',
    'unit': 'us',
    'value': 93.55584184359311},
   {'date': datetime.datetime(2021, 3, 15, 0, 36, 3, tzinfo=tzoffset(None, -14400)),
    'name': 'frequency',
    'unit': 'GHz',
    'value': 5.02968554992376},
   {'date': datetime.datetime(2021, 3, 15, 0, 36, 3, tzinfo=tzoffset(None, -14400)),
    'name': 'anharmonicity',
    'unit': 'GHz',
    'value': -0.33574155258829724},
   {'date': datetime.datetime(2021, 3, 15, 0, 8, 49, tzinfo=tzoffset(None, -14400)),
    'name': 'readout_error',
    'unit': '',
    'value': 0.026100000000000012},
   {'date': datetime.datetime(202

In [14]:
dir(FakeLima().configuration())

['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_channel_qubit_map',
 '_control_channels',
 '_data',
 '_get_channel_prefix_index',
 '_parse_channels',
 '_qubit_channel_map',
 'acquire',
 'acquisition_latency',
 'backend_name',
 'backend_version',
 'basis_gates',
 'channels',
 'conditional',
 'conditional_latency',
 'control',
 'control_channels',
 'coupling_map',
 'credits_required',
 'default_rep_delay',
 'describe',
 'description',
 'discriminators',
 'drive',
 'dt',
 'dtm',
 'dynamic_reprate_enabled',
 'from_dict',
 'gates',
 'get_channel_qubits',
 'get_qubit_channels',
 'hamiltonian',
 'local',
 'max_experiments',
 'max_shots',
 'm

In [15]:
from qiskit.providers.aer.noise import NoiseModel

In [64]:
noise_model = NoiseModel.from_backend(FakeLima())
noise_dict = noise_model.to_dict()['errors']
noise_dict

[{'type': 'qerror',
  'id': '3cedd732c26448179f376d200b9b109e',
  'operations': ['id'],
  'instructions': [[{'name': 'kraus',
     'params': [array([[-0.99997945+0.j,  0.        +0.j],
             [ 0.        +0.j, -0.99968168+0.j]]),
      array([[-0.00641101+0.j,  0.        +0.j],
             [ 0.        +0.j,  0.00641292+0.j]]),
      array([[0.        +0.j, 0.02440096+0.j],
             [0.        +0.j, 0.        +0.j]])],
     'qubits': [0]}]],
  'probabilities': [1.0],
  'gate_qubits': [(0,)]},
 {'type': 'qerror',
  'id': '8d364c2c6f214862a95eaf09f4156172',
  'operations': ['id'],
  'instructions': [[{'name': 'id', 'qubits': [0]},
    {'name': 'kraus',
     'params': [array([[-0.99997658+0.j,  0.        +0.j],
             [ 0.        +0.j, -0.99976255+0.j]]),
      array([[-0.00684392+0.j,  0.        +0.j],
             [ 0.        +0.j,  0.00684538+0.j]]),
      array([[0.        +0.j, 0.02068766+0.j],
             [0.        +0.j, 0.        +0.j]])],
     'qubits': [0]}],
  

In [65]:
from blackwater.data.utils import (
    get_backend_properties_v1,
)

In [66]:
tmp = get_backend_properties_v1(FakeBelem())
tmp

{'name': 'fake_belem',
 'gates_set': ['cx', 'rz', 'id', 'sx', 'x', 'reset'],
 'num_qubits': 5,
 'qubits_props': {0: {'index': 0,
   't1': 8.857848970762537e-05,
   't2': 0.00010679794866226273,
   'readout_error': 0.04139999999999999},
  1: {'index': 1,
   't1': 7.805043996837796e-05,
   't2': 6.376578004446572e-05,
   'readout_error': 0.03200000000000003},
  2: {'index': 2,
   't1': 6.932578590725382e-05,
   't2': 3.8623766504632775e-05,
   'readout_error': 0.02400000000000002},
  3: {'index': 3,
   't1': 5.361400062698815e-05,
   't2': 5.6469814445204655e-05,
   'readout_error': 0.03400000000000003},
  4: {'index': 4,
   't1': 0.00011055756502325884,
   't2': 0.0001316820368187947,
   'readout_error': 0.02059999999999995}},
 'gate_props': {'id_0': {'index': 'id_0',
   'gate_error': 0.00023078387665829674,
   'gate_length': 35.55555555555556},
  'id_1': {'index': 'id_1',
   'gate_error': 0.0004110884185250172,
   'gate_length': 35.55555555555556},
  'id_2': {'index': 'id_2',
   'gate_

In [67]:
tmp.keys()

dict_keys(['name', 'gates_set', 'num_qubits', 'qubits_props', 'gate_props'])

In [68]:
tmp['qubits_props']

{0: {'index': 0,
  't1': 8.857848970762537e-05,
  't2': 0.00010679794866226273,
  'readout_error': 0.04139999999999999},
 1: {'index': 1,
  't1': 7.805043996837796e-05,
  't2': 6.376578004446572e-05,
  'readout_error': 0.03200000000000003},
 2: {'index': 2,
  't1': 6.932578590725382e-05,
  't2': 3.8623766504632775e-05,
  'readout_error': 0.02400000000000002},
 3: {'index': 3,
  't1': 5.361400062698815e-05,
  't2': 5.6469814445204655e-05,
  'readout_error': 0.03400000000000003},
 4: {'index': 4,
  't1': 0.00011055756502325884,
  't2': 0.0001316820368187947,
  'readout_error': 0.02059999999999995}}

In [69]:
t1 = []
t2 = []
readout = []
for val in tmp['qubits_props'].values():
    t1.append(val['t1'])
    t2.append(val['t2'])
    readout.append(val['readout_error'])
print(np.mean(t1))
print(np.mean(t2))
print(np.mean(readout))

8.002525624670083e-05
7.946786929507211e-05
0.030400000000000003


In [70]:
sx = []
x = []
cx = []
reset = []
for key, val in tmp['gate_props'].items():
    if 'sx' == key[:2]:
        sx.append(val['gate_error'])
    elif 'x' == key[0]:
        x.append(val['gate_error'])
    elif 'cx' == key[:2]:
        cx.append(val['gate_error'])
    elif 'reset' in key:
        reset.append(val['gate_error'])
print(np.mean(sx))
print(np.mean(x))
print(np.mean(cx))
print(np.mean(reset))

0.0003886014396357395
0.0003886014396357395
0.013986040396766104
0.0


In [61]:
tmp['gate_props']['reset_1']

{'index': 'reset_1', 'gate_error': 0.0, 'gate_length': 5742.222222222222}

In [52]:
tmp['gate_props'].keys()

dict_keys(['id_0', 'id_1', 'id_2', 'id_3', 'id_4', 'rz_0', 'rz_1', 'rz_2', 'rz_3', 'rz_4', 'sx_0', 'sx_1', 'sx_2', 'sx_3', 'sx_4', 'x_0', 'x_1', 'x_2', 'x_3', 'x_4', 'cx_4_3', 'cx_3_4', 'cx_0_1', 'cx_1_0', 'cx_3_1', 'cx_1_3', 'cx_2_1', 'cx_1_2', 'reset_0', 'reset_1', 'reset_2', 'reset_3', 'reset_4'])

In [48]:
tmp['gate_props']

{'id_0': {'index': 'id_0',
  'gate_error': 0.00019195510390342677,
  'gate_length': 35.55555555555556},
 'id_1': {'index': 'id_1',
  'gate_error': 0.00033064681663890665,
  'gate_length': 35.55555555555556},
 'id_2': {'index': 'id_2',
  'gate_error': 0.0001807726361160903,
  'gate_length': 35.55555555555556},
 'id_3': {'index': 'id_3',
  'gate_error': 0.0003925363414603665,
  'gate_length': 35.55555555555556},
 'id_4': {'index': 'id_4',
  'gate_error': 0.0006789531879417325,
  'gate_length': 35.55555555555556},
 'rz_0': {'index': 'rz_0', 'gate_error': 0, 'gate_length': 0},
 'rz_1': {'index': 'rz_1', 'gate_error': 0, 'gate_length': 0},
 'rz_2': {'index': 'rz_2', 'gate_error': 0, 'gate_length': 0},
 'rz_3': {'index': 'rz_3', 'gate_error': 0, 'gate_length': 0},
 'rz_4': {'index': 'rz_4', 'gate_error': 0, 'gate_length': 0},
 'sx_0': {'index': 'sx_0',
  'gate_error': 0.00019195510390342677,
  'gate_length': 35.55555555555556},
 'sx_1': {'index': 'sx_1',
  'gate_error': 0.0003306468166389066

In [77]:
from qiskit_aer import AerSimulator, QasmSimulator
from noise_utils import AddNoise
backend = FakeBelem()
properties = get_backend_properties_v1(backend)

# Local, coherent noise
backend_ideal = QasmSimulator() # Noiseless
backend_noisy_coherent, noise_model = AddNoise(backend=backend).add_coherent_noise(seed=0, theta=np.pi * 0.04, uniform=False, add_depolarization=True)

run_config_ideal = {'shots': 10000, 'backend': backend_ideal, 'name': 'ideal'}
run_config_noisy_coherent = {'shots': 10000, 'backend': backend_noisy_coherent, 'name': 'noisy_coherent'}

random seed fixed to 0
thetas [0.06896594 0.08987335 0.07574548 0.06847204 0.05323803 0.08116545
 0.05498883 0.1120635 ]


/Users/haoranliao/anaconda3/envs/mlqem/lib/python3.8/site-packages/numpy/linalg/linalg.py:2139: RuntimeWarning: divide by zero encountered in det
  r = _umath_linalg.det(a, signature=signature)
/Users/haoranliao/anaconda3/envs/mlqem/lib/python3.8/site-packages/numpy/linalg/linalg.py:2139: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)


In [76]:
np.mean([0.06896594, 0.08987335, 0.07574548, 0.06847204, 0.05323803, 0.08116545,
 0.05498883, 0.1120635])

0.0755640775

In [78]:
np.mean([0.06896594, 0.08987335, 0.07574548, 0.06847204, 0.05323803, 0.08116545, 0.05498883, 0.1120635])

0.0755640775