In [1]:
import torch
import numpy as np

In [32]:
X = torch.zeros((3, 5))
a = torch.tensor([1, 2, 3])
# b = torch.tensor([2, 2])
print(b.shape)
print(b[None, :].shape)

X[:, -3:] = a
# X[:, :2] = b[None, :]
X

torch.Size([2])
torch.Size([1, 2])


tensor([[0., 0., 1., 2., 3.],
        [0., 0., 1., 2., 3.],
        [0., 0., 1., 2., 3.]])

In [35]:
a = torch.tensor(9)
X[:, -3:] = a
X

tensor([[0., 0., 9., 9., 9.],
        [0., 0., 9., 9., 9.],
        [0., 0., 9., 9., 9.]])

In [6]:
Y = np.zeros((10, 6))
a = 9
Y[:, -3:] = [a]

In [7]:
Y

array([[0., 0., 0., 9., 9., 9.],
       [0., 0., 0., 9., 9., 9.],
       [0., 0., 0., 9., 9., 9.],
       [0., 0., 0., 9., 9., 9.],
       [0., 0., 0., 9., 9., 9.],
       [0., 0., 0., 9., 9., 9.],
       [0., 0., 0., 9., 9., 9.],
       [0., 0., 0., 9., 9., 9.],
       [0., 0., 0., 9., 9., 9.],
       [0., 0., 0., 9., 9., 9.]])